### ISSUE TITLE
Conexão entre jogadores

### ISSUE THREAD

**Issue by CesarJava** [rafaelfiviola/minesweeperdistributed#9]
- [ ] Listar os Servidores na janela de listar

- [ ] Depois de conectar, configurar a String de conexão:
- - [ ] Conectar, criar uma String global no padrão: "IP:porta"

**Comment by rafaelfiviola** [comment]
A janela agora atualiza quando clica-se no botão procurar e adiciona uma lista com os servidores, também foi adicionado o método getIpAndPort à classe ServerInfo que retorna o ip e a porta no formato dito acima.
